// Runs inside an isolated headless Chromium fixture, never in the user's app.
(async () => {
  const output = document.createElement("pre"); output.id = "smoke-result"; document.body.append(output);
  const wait = async (test, label, timeout = 10000) => {
    const deadline = Date.now() + timeout;
    while (!test()) { if (Date.now() > deadline) throw new Error(`Timed out: ${label}`); await new Promise((resolve) => setTimeout(resolve, 50)); }
  };
  const shadow = () => document.querySelector("#mods-for-t3-code-host").shadowRoot;
  const panelShadow = () => document.querySelector('[data-t3mods="panels"]')?.shadowRoot;
  const click = (title) => {
    const control = [...shadow().querySelectorAll("button"), ...(panelShadow()?.querySelectorAll("button") ?? [])].find((item) => item.textContent === title);
    if (!control) throw new Error(`Missing button: ${title}`);
    control.click();
  };
  const assert = (value, text) => { if (!value) throw new Error(text); };
  const results = [];
  try {
    await wait(() => window.__modsForT3Code, "host startup");
    assert(document.querySelector('[data-t3mods="sidebar-button"]'), "Sidebar Mods icon is present");
    const focus = await (await fetch("/focus-timer.t3mod")).json();
    await window.__modsForT3Code.importCandidate(focus); click("Install mod");
    await wait(() => shadow().querySelector('input[aria-label="Enable Focus timer"]'), "install completion");
    assert(shadow().querySelector('input[aria-label="Enable Focus timer"]').checked, "Confirmed installation enables the mod"); results.push("permission review and automatic enable");
    await wait(() => panelShadow()?.querySelector(".panel h2")?.textContent === "25:00", "worker panel");
    click("Close"); click("Start");
    await wait(() => panelShadow()?.querySelector(".panel h2")?.textContent !== "25:00", "timer action"); results.push("sandbox worker and live panel actions");
    window.__modsForT3Code.open();
    shadow().querySelector('input[aria-label="Enable Focus timer"]').click();
    await wait(() => !document.querySelector("iframe") && !panelShadow()?.querySelector(".panel") && !shadow().querySelector('input[aria-label="Enable Focus timer"]').disabled, "live disable"); results.push("immediate disable and cleanup");
    shadow().querySelector('input[aria-label="Enable Focus timer"]').click();
    await wait(() => panelShadow()?.querySelector(".panel"), "live enable"); results.push("live enable without reload");
    history.pushState({}, "", "/settings/appearance"); document.body.append(document.createComment("trigger settings observation"));
    await wait(() => document.querySelector('[data-t3mods="settings-section"]'), "settings entry"); results.push("Settings Mods section");
    document.querySelector('[data-t3mods="settings-section"] button').click();
    assert(document.querySelector("main").style.display === "none" && shadow().querySelector("dialog[data-inline]"), "Mods opens inline in Settings content");
    window.__modsForT3Code.open("create");
    assert(document.querySelector("main").style.display === "" && !shadow().querySelector("dialog[data-inline]"), "Leaving inline Settings restores T3 content"); results.push("inline Settings content and restore");
    const description = shadow().querySelector("textarea"); description.value = "A short break reminder";
    click("Draft in T3");
    await wait(() => document.querySelector('[data-testid="composer-editor"]').innerText.includes("A short break reminder"), "AI composer draft");
    assert(document.querySelector('[data-testid="composer-editor"]').innerText.includes("API version 1"), "Author prompt includes SDK"); results.push("AI request through existing composer");
    const sandboxTest = { format: "t3mod/1", manifest: { apiVersion: 1, id: "isolation-test", version: "1.0.0", name: "Isolation test", description: "Checks isolation", author: "Test", permissions: ["ui.panels"] }, code: 'globalThis.T3Mod={async activate(api){let blocked=false;try{await fetch("http://127.0.0.1:4318/")}catch{blocked=true}let denied=false;try{await api.draft.read()}catch{denied=true}await api.panels.set({title:"Isolation result",body:JSON.stringify({blocked,denied,dom:typeof document,node:typeof process})});}};' };
    await window.__modsForT3Code.importCandidate(sandboxTest); click("Install mod");
    await wait(() => shadow().querySelector('input[aria-label="Enable Isolation test"]'), "isolation mod install");
    await wait(() => [...panelShadow().querySelectorAll(".panel h2")].some((item) => item.textContent === "Isolation result"), "isolation panel");
    const panel = [...panelShadow().querySelectorAll(".panel")].find((item) => item.querySelector("h2").textContent === "Isolation result");
    const value = JSON.parse(panel.querySelector("p").textContent);
    assert(value.blocked && value.denied && value.dom === "undefined" && value.node === "undefined", "Network, ungranted draft access, DOM and Node are blocked"); results.push("network and capability isolation");
    const telemetry = window.__T3_MODS_TELEMETRY__.__test; telemetry.reset();
    history.pushState({}, "", "/local/thread-a");
    const dock = () => document.querySelector('[data-t3mods="bands"]');
    const band = () => dock()?.shadowRoot.querySelector('.band[data-mod="token-weather"]');
    const bandText = () => band()?.textContent ?? "";
    const tone = () => band()?.firstElementChild?.dataset.tone;
    const sparkline = () => [...(band()?.children ?? [])].map((part) => part.textContent.trim()).find((text) => /^[▁▂▃▄▅▆▇█]+$/.test(text)) ?? "";
    const shows = (text, label) => wait(() => bandText().includes(text), `${label}: expected "${text}"`);
    const measure = (usedTokens, extra = {}) => telemetry.emit({ threadId: "thread-a", turnId: "turn-1", usedTokens, maxTokens: 200000, ...extra });
    window.__modsForT3Code.open("examples");
    const weatherRow = [...shadow().querySelectorAll("article.row")].find((item) => item.querySelector("h2")?.textContent === "Token weather");
    assert(weatherRow, "Token weather is a built-in mod"); weatherRow.querySelector("button").click();
    assert(shadow().textContent.includes("ui.band") && shadow().textContent.includes("session.usage"), "Band and usage permissions are reviewed");
    click("Install mod");
    await wait(() => !shadow().querySelector('[aria-busy]') && shadow().textContent.includes("Installed and switched on."), "weather install");
    window.__modsForT3Code.open();
    assert(shadow().querySelector('input[aria-label="Enable Token weather"]').checked, "Weather automatically enabled");
    await wait(() => !band(), "no weather before a measurement");
    const form = document.querySelector("[data-chat-composer-form]");
    for (const [used, text, color] of [[40000, "☀ Clear", "yellow"], [50000, "☁ Cloudy", "cyan"], [120000, "☂ Showers", "blue"], [178000, "☇ Storm", "magenta"], [180000, "↯ Compact soon", "red"]]) {
      measure(used); await shows(text, "weather bin"); assert(tone() === color, `${text} uses ${color}`);
    }
    assert(dock().nextElementSibling === form && !form.contains(dock()) && !document.querySelector('[data-testid="composer-editor"]').contains(dock()), "Band is above the composer and outside the editor");
    assert(bandText().includes("90%") && bandText().includes("180k / 200k"), "Percent and measured tokens shown"); results.push("measured weather bins and tones");
    measure(36100, { complete: true }); await shows("36.1k / 200k", "first completed turn");
    assert(!/unknown|first turn|last turn|Δ/.test(bandText()), "First turn omits delta placeholders");
    measure(120000, { turnId: "turn-2" }); await shows("60%", "running turn");
    assert(sparkline().length === 1 && !bandText().includes("last turn"), "Running turns stay out of history");
    measure(134400, { turnId: "turn-2", complete: true }); await shows("▲ +98.3k last turn", "completed delta");
    assert(bandText().includes("67%") && bandText().includes("134.4k / 200k") && sparkline().length === 2, "Completed turn recorded once");
    measure(140000, { turnId: "turn-2", complete: true }); await shows("▲ +103.9k last turn", "same-turn final measurement");
    assert(sparkline().length === 2, "Same turn replaced, not appended");
    measure(50000, { turnId: "turn-3", complete: true }); await shows("▼ −90k last turn", "compaction drop"); results.push("completed-turn sparkline, deltas, and compaction");
    measure(60000, { turnId: "turn-4", maxTokens: null }); await shows("window size unavailable", "unknown window");
    assert(!bandText().includes("200k") && !bandText().includes("%"), "Unknown window is never assumed");
    telemetry.emit({ threadId: "thread-b", turnId: "other", usedTokens: 1000, maxTokens: 200000 });
    await new Promise((resolve) => setTimeout(resolve, 300));
    assert(bandText().includes("window size unavailable"), "Another thread's usage is ignored");
    history.pushState({}, "", "/local/thread-c"); await wait(() => !band(), "route without usage hides weather");
    history.pushState({}, "", "/local/thread-b"); await shows("0%", "route to measured thread");
    history.pushState({}, "", "/local/thread-a"); await shows("window size unavailable", "route back");
    assert(sparkline().length === 3, "Per-thread history kept"); results.push("unknown window, thread filtering, and route refresh");
    const replacement = form.cloneNode(true); form.replaceWith(replacement);
    await wait(() => dock()?.nextElementSibling === replacement, "reattach after React rerender");
    dock().remove(); await wait(() => dock()?.nextElementSibling === replacement, "reattach after removal"); results.push("band reattaches after rerenders");
    window.__modsForT3Code.open(); shadow().querySelector('input[aria-label="Enable Token weather"]').click();
    await wait(() => !dock() && !shadow().querySelector('input[aria-label="Enable Token weather"]').disabled, "band hot cleanup");
    shadow().querySelector('input[aria-label="Enable Token weather"]').click();
    await shows("window size unavailable", "re-enabled weather"); await wait(() => sparkline().length === 3, "stored history");
    results.push("band hot cleanup and stored history");
    document.documentElement.style.setProperty("--background", "#202027");
    const theme = { ...sandboxTest, manifest: { ...sandboxTest.manifest, id: "theme-test", name: "Theme test", permissions: ["ui.theme"] }, code: 'globalThis.T3Mod={async activate(api){await api.theme.set({background:"#101820",foreground:"#f0f4f8"})}};' };
    await window.__modsForT3Code.importCandidate(theme); click("Install mod");
    await wait(() => shadow().querySelector('input[aria-label="Enable Theme test"]'), "theme install");
    await wait(() => document.documentElement.style.getPropertyValue("--background") === "#101820", "theme applied");
    await wait(() => !shadow().querySelector('input[aria-label="Enable Theme test"]').disabled, "theme toggle ready");
    shadow().querySelector('input[aria-label="Enable Theme test"]').click();
    await wait(() => document.documentElement.style.getPropertyValue("--background") === "#202027", "theme restored");
    await wait(() => !shadow().querySelector('input[aria-label="Enable Theme test"]').disabled, "theme toggle settled"); results.push("theme apply and restore");
    const failure = { ...sandboxTest, manifest: { ...sandboxTest.manifest, id: "broken-mod", name: "Broken mod" }, code: 'globalThis.T3Mod={activate(){while(true){}}};' };
    await window.__modsForT3Code.importCandidate(failure); click("Install mod");
    await wait(() => shadow().querySelector('input[aria-label="Enable Broken mod"]'), "broken mod install");
    await wait(() => [...shadow().querySelectorAll(".error")].some((item) => /startup|responding/.test(item.textContent)), "runaway quarantine", 12000);
    assert(!shadow().querySelector('input[aria-label="Enable Broken mod"]').checked, "Runaway mod disabled"); results.push("runaway worker quarantine");
    await window.__modsForT3Code.dispose();
    assert(!document.querySelector("iframe") && !document.querySelector('[data-t3mods="bands"]'), "All workers and bands removed on disposal");
    output.dataset.status = "passed"; output.textContent = results.join("\n");
  } catch (error) { output.dataset.status = "failed"; output.textContent = error.stack + "\nHost state:\n" + (document.querySelector("#mods-for-t3-code-host")?.shadowRoot?.textContent ?? "missing host").slice(-6000); }
})();
