// Mirrors T3's own tokens and control metrics (settings rows, xs/sm buttons, switches,
// dialogs) so owned UI reads as part of the app. Colors come only from T3 variables.
export const style: string = `
:host{--mf-fg:var(--foreground,#f5f5f5);--mf-muted:var(--muted-foreground,#a1a1aa);--mf-border:var(--border,#ffffff14);--mf-input:var(--input,var(--mf-border));--mf-bg:var(--background,#0a0a0a);--mf-card:var(--card,var(--mf-bg));--mf-popover:var(--popover,var(--mf-bg));--mf-accent:var(--accent,color-mix(in srgb,var(--mf-fg) 6%,transparent));--mf-primary:var(--primary,#3b82f6);--mf-primary-fg:var(--primary-foreground,#fff);--mf-ring:var(--ring,var(--mf-muted));--mf-danger:var(--destructive,#ef4444);--mf-radius:var(--radius,.625rem);--mf-control-radius:var(--control-radius,calc(var(--mf-radius) - 2px));font:13px/1.5 var(--font-sans,-apple-system,BlinkMacSystemFont,"Segoe UI",system-ui,sans-serif);color:var(--mf-fg);color-scheme:inherit;-webkit-font-smoothing:antialiased}
*{box-sizing:border-box}h1,h2,h3,p{margin:0}button,input,textarea{font:inherit;color:inherit}
:focus-visible{outline:2px solid color-mix(in srgb,var(--mf-ring) 60%,transparent);outline-offset:1px}
button{display:inline-flex;align-items:center;justify-content:center;gap:6px;height:28px;padding:0 9px;border:1px solid var(--mf-input);border-radius:var(--mf-control-radius);background:color-mix(in srgb,var(--mf-input) 32%,transparent);font-size:13px;font-weight:500;white-space:nowrap;cursor:pointer;transition:background-color .15s,color .15s,border-color .15s}
button:hover{background:color-mix(in srgb,var(--mf-accent) 60%,transparent)}button:disabled{opacity:.64;cursor:default;pointer-events:none}
button.primary{background:var(--mf-primary);border-color:var(--mf-primary);color:var(--mf-primary-fg)}button.primary:hover{background:color-mix(in srgb,var(--mf-primary) 90%,transparent)}
button.ghost,button.danger{background:transparent;border-color:transparent;color:var(--mf-muted)}button.ghost:hover,button.danger:hover{background:var(--mf-accent);color:var(--mf-fg)}button.danger:hover{color:var(--mf-danger)}
button.destructive{background:var(--mf-danger);border-color:var(--mf-danger);color:#fff}
button.xs{height:24px;padding:0 7px;font-size:12px;gap:4px}button.icon{width:28px;padding:0}button.icon.xs{width:24px}button svg{width:16px;height:16px;flex:none}
input.switch{appearance:none;-webkit-appearance:none;position:relative;flex:none;width:32px;height:20px;margin:0;padding:0;border:1px solid color-mix(in srgb,var(--mf-fg) 14%,transparent);border-radius:999px;background:color-mix(in srgb,var(--mf-fg) 20%,transparent);cursor:pointer;transition:background-color .2s,border-color .2s}
input.switch::after{content:"";position:absolute;top:1px;left:1px;width:16px;height:16px;border-radius:50%;background:#fff;box-shadow:0 1px 2px #0003;transition:transform .2s}
input.switch:checked{background:var(--mf-primary);border-color:var(--mf-primary)}input.switch:checked::after{transform:translateX(12px)}input.switch:disabled{opacity:.64;cursor:default}
input[type=search],input[type=text],textarea{display:block;width:100%;min-height:32px;padding:5px 10px;border:1px solid var(--mf-input);border-radius:var(--mf-control-radius);background:color-mix(in srgb,var(--mf-input) 32%,transparent);font-size:13px;outline:none}
input[type=search]:focus-visible,textarea:focus-visible{border-color:var(--mf-ring);outline:2px solid color-mix(in srgb,var(--mf-ring) 24%,transparent);outline-offset:0}
textarea{min-height:96px;max-height:240px;resize:vertical;line-height:1.5}::placeholder{color:color-mix(in srgb,var(--mf-muted) 72%,transparent)}
dialog{padding:0;margin:auto;border:1px solid var(--mf-border);border-radius:calc(var(--mf-radius) + 6px);background:var(--mf-popover);color:inherit;box-shadow:0 16px 48px #0000002e;width:min(640px,calc(100vw - 32px));height:min(600px,calc(100vh - 64px));overflow:hidden}
dialog[open]{display:flex;flex-direction:column}dialog::backdrop{background:#00000052}
dialog.ask{width:min(420px,calc(100vw - 32px));height:fit-content;max-height:calc(100vh - 64px)}dialog.ask .content{flex:0 1 auto;padding-top:4px;scrollbar-gutter:auto}dialog.ask .explain{max-height:40vh;overflow:auto}
header{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;padding:20px 20px 12px;flex:none}header h1{font-size:15px;font-weight:600;line-height:20px;letter-spacing:-.01em}header p{margin-top:2px;font-size:12px;color:var(--mf-muted)}.header-actions{display:flex;align-items:center;gap:4px;margin:-2px -6px 0 0}
.tabs{display:flex;align-items:center;gap:2px;flex:none;margin:0 20px 4px;padding:2px;width:max-content;max-width:calc(100% - 40px);overflow-x:auto;border-radius:calc(var(--mf-control-radius) + 2px);background:color-mix(in srgb,var(--mf-fg) 5%,transparent)}
.tabs button{height:24px;padding:0 10px;border:0;background:transparent;color:var(--mf-muted);font-size:12px}.tabs button:hover{color:var(--mf-fg);background:transparent}.tabs button[aria-selected=true]{background:color-mix(in srgb,var(--mf-fg) 10%,transparent);color:var(--mf-fg)}
.content{flex:1;min-height:0;overflow-y:auto;overscroll-behavior:contain;padding:16px 20px 20px;display:flex;flex-direction:column;gap:20px;scrollbar-gutter:stable}
.section{display:flex;flex-direction:column;gap:8px}.section-head{display:flex;align-items:center;justify-content:space-between;gap:8px;min-height:20px;padding:0 4px}
.section-head h2{display:flex;align-items:center;gap:8px;font-size:11px;font-weight:600;letter-spacing:.08em;text-transform:uppercase;color:color-mix(in srgb,var(--mf-fg) 50%,transparent)}.section-head h2::before{content:"";width:12px;height:1px;background:var(--mf-border)}
.card{border:1px solid var(--mf-border);border-radius:calc(var(--mf-radius) + 6px);background:var(--mf-card)}.card>.body{padding:14px 16px;display:flex;flex-direction:column;gap:8px}
.row{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:12px 16px;border-top:1px solid var(--mf-border)}.row:first-child{border-top:0}
.row-text{min-width:0;flex:1;display:flex;flex-direction:column;gap:2px}.row h2{display:flex;align-items:center;gap:6px;font-size:13px;font-weight:600;letter-spacing:-.01em;line-height:20px}.row p{font-size:12px;line-height:1.5;color:color-mix(in srgb,var(--mf-muted) 85%,transparent)}
.row-actions{display:flex;align-items:center;gap:4px;flex:none}.row-actions input.switch{margin-left:8px}
.meta{font-size:11px;color:var(--mf-muted);font-variant-numeric:tabular-nums}.state{font-size:11px;font-weight:500;line-height:16px;padding:0 6px;border-radius:999px;color:var(--mf-muted);background:color-mix(in srgb,var(--mf-fg) 7%,transparent)}.state[data-state=active]{color:var(--mf-fg)}
.state[data-state=active]::before,.state[data-state=starting]::before{content:"";display:inline-block;width:6px;height:6px;margin-right:4px;border-radius:50%;vertical-align:1px;background:var(--success,var(--color-emerald-500,#10b981))}.state[data-state=starting]::before{background:var(--mf-muted);animation:mf-pulse 1.2s ease-in-out infinite}
.state[data-state=stopped]{color:var(--mf-danger);background:color-mix(in srgb,var(--mf-danger) 12%,transparent)}.state[data-state=pending]{color:var(--mf-primary);background:color-mix(in srgb,var(--mf-primary) 14%,transparent)}
@keyframes mf-pulse{50%{opacity:.35}}@media(prefers-reduced-motion:reduce){.state[data-state=starting]::before{animation:none}}
.tabs .count{min-width:16px;height:16px;padding:0 4px;border-radius:999px;background:var(--mf-primary);color:var(--mf-primary-fg);font-size:10px;font-weight:600;line-height:16px;text-align:center;font-variant-numeric:tabular-nums}
.flash{padding:8px 12px;border:1px solid var(--mf-border);border-radius:var(--mf-control-radius);font-size:12px;line-height:1.5;color:var(--mf-muted);white-space:pre-wrap;overflow-wrap:anywhere}.flash[data-tone=error]{color:var(--mf-danger);border-color:color-mix(in srgb,var(--mf-danger) 35%,transparent);background:color-mix(in srgb,var(--mf-danger) 7%,transparent)}
.steps{margin:0;padding-left:18px;display:flex;flex-direction:column;gap:2px;font-size:12px;line-height:1.5;color:var(--mf-muted)}
textarea.code{min-height:120px;font:11px/1.6 var(--font-mono,ui-monospace,SFMono-Regular,Menlo,monospace);white-space:pre;overflow-wrap:normal}
.card>.row+.body{border-top:1px solid var(--mf-border)}.actions .start{margin-right:auto}.notice .actions{justify-content:flex-start;margin-top:6px}
.explain{font-size:12px;line-height:1.5;color:var(--mf-muted)}.content>.explain{padding:0 4px}.permission span{font-size:13px}.sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0 0 0 0);white-space:nowrap}.error{font-size:12px;color:var(--mf-danger);white-space:pre-wrap}label{font-size:12px;font-weight:500}
.permission code,.review code{font:11px/1.4 var(--font-mono,ui-monospace,SFMono-Regular,Menlo,monospace);color:var(--mf-muted)}
.review-title{display:flex;flex-direction:column;gap:2px}.review-title h2{font-size:15px;font-weight:600;line-height:20px}
details{font-size:12px}summary{cursor:pointer;color:var(--mf-muted);padding:2px 4px}summary:hover{color:var(--mf-fg)}
.review-code,.log{margin:8px 0 0;padding:10px 12px;max-height:220px;overflow:auto;border:1px solid var(--mf-border);border-radius:var(--mf-control-radius);background:color-mix(in srgb,var(--mf-fg) 3%,transparent);font:11px/1.6 var(--font-mono,ui-monospace,SFMono-Regular,Menlo,monospace);white-space:pre-wrap;overflow-wrap:anywhere}
.card>.log{margin:0;border:0;border-radius:inherit;max-height:none;min-height:120px;background:transparent}
.actions{display:flex;align-items:center;justify-content:flex-end;gap:8px}.footer{flex:none;padding:12px 20px;border-top:1px solid var(--mf-border);background:color-mix(in srgb,var(--mf-fg) 2%,transparent)}
.menu{position:fixed;z-index:10;min-width:140px;padding:4px;display:flex;flex-direction:column;border:1px solid var(--mf-border);border-radius:var(--mf-radius);background:var(--mf-popover);box-shadow:0 8px 24px #00000029}
.menu button{justify-content:flex-start;height:28px;padding:0 8px;border:0;border-radius:calc(var(--mf-radius) - 4px);background:transparent;color:var(--mf-fg);font-weight:400;outline:none}.menu button:hover,.menu button:focus-visible{background:var(--mf-accent)}.menu button.danger{color:var(--mf-danger)}
.decision-preview{white-space:pre-wrap;overflow-wrap:anywhere}
:host([data-inline]){display:flex;flex-direction:column;flex:1;min-height:0}
dialog[data-inline]{position:static;flex:1;min-height:0;width:100%;height:auto;max-width:none;max-height:none;margin:0;border:0;border-radius:0;box-shadow:none;background:transparent}
dialog[data-inline]>header,dialog[data-inline]>.content,dialog[data-inline]>.footer{padding-inline:max(24px,calc((100% - 48rem) / 2))}dialog[data-inline]>.tabs{margin-inline:max(24px,calc((100% - 48rem) / 2))}dialog[data-inline]>header{padding-top:24px}dialog[data-inline]>.content{padding-bottom:32px}dialog[data-inline]>.footer{background:transparent}
.notice{position:fixed;right:16px;bottom:16px;z-index:1000;width:min(340px,calc(100vw - 32px));display:flex;flex-direction:column;gap:2px;padding:10px 12px;border:1px solid var(--mf-border);border-radius:var(--mf-radius);background:var(--mf-popover);box-shadow:0 8px 24px #00000024;font-size:13px}.notice strong{font-size:12px;font-weight:600}.notice span{color:var(--mf-muted);font-size:12px}
.panel-tray{position:fixed;right:16px;bottom:16px;z-index:999;width:300px;max-height:60vh;overflow:auto;border:1px solid var(--mf-border);border-radius:var(--mf-radius);background:var(--mf-popover);box-shadow:0 8px 24px #00000024}
.panel-tray header{align-items:center;padding:6px 6px 6px 10px;font-size:11px;font-weight:600;letter-spacing:.08em;text-transform:uppercase;color:color-mix(in srgb,var(--mf-fg) 50%,transparent)}
.panel{padding:10px;border-top:1px solid var(--mf-border)}.panel h2{font-size:13px;font-weight:600;margin:1px 0 4px}.panel p{font-size:12px;line-height:1.5;color:var(--mf-muted);white-space:pre-wrap}.panel .actions{justify-content:flex-start;flex-wrap:wrap;gap:4px;margin-top:8px}
.panel-tray[data-docked]{position:relative;inset:auto;width:100%;max-height:30vh;box-shadow:none;z-index:auto;margin-bottom:8px;background:var(--mf-card)}
@media(max-width:600px){header{padding:16px 16px 10px}.tabs{margin-inline:16px;max-width:calc(100% - 32px)}.content{padding:12px 16px 16px}.row{flex-direction:column;align-items:stretch;gap:8px}.row-actions{justify-content:flex-start;flex-wrap:wrap}.panel-tray{width:280px}}
.band-stack{width:fit-content;max-width:100%;padding:2px 16px 6px;border-top-right-radius:var(--mf-control-radius);background:var(--mf-bg);font-size:12px;line-height:16px;color:var(--mf-muted)}.band{white-space:pre;overflow:hidden;text-overflow:ellipsis;font-variant-numeric:tabular-nums}.band [data-tone=muted]{color:var(--mf-muted)}.band [data-tone=yellow]{color:var(--color-yellow-500,#d4a72c)}.band [data-tone=cyan]{color:var(--color-cyan-500,#22a8bd)}.band [data-tone=blue]{color:var(--info,var(--color-blue-500,#3b82f6))}.band [data-tone=magenta]{color:var(--color-fuchsia-500,#c85bd8)}.band [data-tone=red]{color:var(--destructive,#e5534b)}
.context-widget{display:flex;align-items:center;gap:3px;pointer-events:auto}.context-widget[hidden]{display:none}.context-trigger{width:auto;min-width:28px;height:28px;padding:4px;gap:3px}.context-trigger svg{width:20px;height:20px;transform:rotate(-90deg)}.context-ring-track{stroke:color-mix(in srgb,var(--mf-muted) 24%,transparent)}.context-ring-fill{stroke:color-mix(in srgb,var(--mf-muted) 72%,transparent);stroke-linecap:round;transition:stroke-dashoffset .5s ease-out,stroke .5s ease-out}.context-widget[data-level=high] .context-ring-fill{stroke:var(--color-error,var(--mf-danger))}.context-widget[data-unknown=true] .context-ring-track{stroke-dasharray:3 3}.context-percent:empty{display:none}.context-percent{font-size:11px;color:var(--mf-muted);font-variant-numeric:tabular-nums}
.context-popup{position:fixed;inset:auto;margin:0;width:min(430px,calc(100vw - 24px));max-height:calc(100vh - 24px);overflow:auto;padding:0;border:1px solid var(--mf-border);border-radius:calc(var(--mf-radius) + 4px);background:var(--mf-popover);color:var(--mf-fg);box-shadow:0 8px 24px #00000029;pointer-events:auto;white-space:normal}.context-header{padding:12px 16px 4px;align-items:center;gap:12px}.context-header h2{font-size:13px;font-weight:500;color:var(--mf-muted)}.context-content{padding:8px 16px 16px;display:flex;flex-direction:column;gap:12px}.context-summary{display:flex;justify-content:space-between;flex-wrap:wrap;gap:4px 12px;font-size:12px;color:var(--mf-muted);font-variant-numeric:tabular-nums}.context-bar{display:flex;gap:1px;height:6px;flex:none;overflow:hidden;border-radius:999px;background:color-mix(in srgb,var(--mf-muted) 24%,transparent)}.context-segment{height:100%;flex-shrink:1;border-radius:2px}.context-breakdown{display:flex;flex-direction:column;gap:10px;margin:2px 0 0;font-size:12px}.context-category{display:flex;align-items:center;justify-content:space-between;gap:16px}.context-category dt{display:flex;align-items:center;gap:8px;min-width:0}.context-category dd{margin:0;color:var(--mf-muted);font-variant-numeric:tabular-nums;flex:none}.context-category .context-unavailable{font-size:11px;color:color-mix(in srgb,var(--mf-muted) 75%,transparent)}.context-swatch{width:10px;height:10px;flex:none;border-radius:2px}.context-note{font-size:11px;line-height:1.5;color:var(--mf-muted)}@media(prefers-reduced-motion:reduce){.context-ring-fill{transition:none}}
`;
